### PR TITLE
Update sauce-connect.rb

### PR DESCRIPTION
**Pull request by markrusciano-wf**

### CODE REVIEW

**Comment by raphaeladam-wf** [comment]
@markrusciano-wf Is there anything specific you're wanting with this update? https://support.saucelabs.com/customer/portal/articles/2060408-sauce-connect-4-3-10-released

**Comment by raphaeladam-wf** [comment]
+1

**Comment by raphaeladam-wf** [comment]
@tylersnavely-wf @matthewbalvanz-wf

**Comment by tylersnavely-wf** [comment]
+1

**Pull request merged**
